version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing Typescript...
      - npm install -g typescript
      - echo Installing Dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`
      
cache:
  paths:
    - 'node_modules/**/*'
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  name: wav-planet-$(date +%Y-%m-%d)


